Chapter 13: User microposts
linhherrera96/sample_app pull request #11
Opened 2018-03-08 03:24 UTC by linhherrera96

![screenshot from 2018-03-08 10-21-12](https://user-images.githubusercontent.com/35018289/37131398-d6a4fc2a-22ba-11e8-970d-7f2099dd47f2.png)

2018-03-08 03:24 UTC, linhherrera96 commented
ready

2018-03-08 03:58 UTC, phamvanbk11 commented on Gemfile
> +  gem 'fog', '1.42'
nháy " nhé

2018-03-08 03:58 UTC, phamvanbk11 commented on app/assets/javascripts/micropost_javascript.js
> +    alert("Maximum file size is 5MB. Please choose a smaller file.");
Tìm hiểu I18njs dùng nhé em

2018-03-08 03:58 UTC, phamvanbk11 commented
commented

2018-03-08 04:18 UTC, linhherrera96 commented
ready

2018-03-08 06:21 UTC, chien-pv commented on app/assets/javascripts/micropost_javascript.js
> + 	});
indent

2018-03-08 06:21 UTC, chien-pv commented on app/views/microposts/_micropost.html.erb
> +    Posted <%= time_ago_in_words(micropost.created_at) %> ago.
I18n

2018-03-08 06:21 UTC, chien-pv commented
commented

2018-03-08 08:23 UTC, linhherrera96 commented
ready

2018-03-08 09:04 UTC, VuThiTranVan requested changes

2018-03-08 09:04 UTC, VuThiTranVan commented on app/assets/stylesheets/custom.scss
> +    border-top: 1px solid #e8e8e8;
Ủa khai báo mã màu mak sao ko dùng

2018-03-08 09:04 UTC, VuThiTranVan commented on app/controllers/microposts_controller.rb
> +    @micropost = current_user.microposts.build micropost_params
Buil với new khác nhau thế nào e

2018-03-08 09:12 UTC, VuThiTranVan commented on app/helpers/microposts_helper.rb
> +end
reemove file

2018-03-08 09:12 UTC, VuThiTranVan commented on app/models/micropost.rb
> +  validates :user_id, presence: true
chi ri thanh niên, self check ri đây thì ăn (tat) nhé

2018-03-08 09:12 UTC, VuThiTranVan commented on app/models/micropost.rb
> +  validate  :picture_size
1 space thôi em ơi

2018-03-08 09:12 UTC, VuThiTranVan commented on app/models/micropost.rb
> +  scope :swap, ->{order(created_at: :desc)}
scope tên gì khó hiểu vậy?
đặt là newest hoặc lastest nhé

2018-03-08 09:12 UTC, VuThiTranVan commented on app/views/microposts/_micropost.html.erb
> +    <% t ("microposts.micropost_html.post") <%= time_ago_in_words(micropost.created_at) %> <% t ("microposts.micropost_html.ago") %>
dòng ni mà chạy dc hà em
`<% t` ???
đúng phải là `<%= t ` chứ

2018-03-08 09:12 UTC, VuThiTranVan commented on test/controllers/microposts_controller_test.rb
> +  # end
xóa comment

2018-03-08 09:12 UTC, VuThiTranVan commented on test/models/micropost_test.rb
> +  # end
xóa comment

2018-03-08 09:13 UTC, VuThiTranVan commented
commented
check lại mấy cái image cái mô ko dùng thì xóa, đưa lên đây làm gì, tính ăn x đúng hem
picture/3/So_Hyun.png

2018-03-09 01:00 UTC, linhherrera96 commented on app/controllers/microposts_controller.rb
> +    @micropost = current_user.microposts.build micropost_params
theo e nghĩ build được gọi thông qua object cụ thể còn new thông qua tên lớp Model.,build cũng giống như new là trả về 1 object trong bộ nhớ nhưng nó không sửa csdl

2018-03-09 01:00 UTC, linhherrera96 commented
ready

2018-03-09 02:57 UTC, phamvanbk11 commented
merged

2018-03-09 02:57 UTC, phamvanbk11 commented on app/controllers/microposts_controller.rb
> +    @micropost = current_user.microposts.build micropost_params
tìm hiểu thêm nhé

2018-03-09 02:58 UTC, merged